project_id = "fziapohwzcbcfumaffeo"

[functions.validate-pdf-upload]
verify_jwt = false

[functions.upload-question-paper]
verify_jwt = false

[functions.upload-files]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
